### ISSUE TITLE
Fix develop 

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/ecbuild#12]
The develop branch of our jcsda fork of ecbuild is both broken and behind.   By broken, I mean that when I use it in the containers (and other places, like discover with the jedi-stack modules), it can't find netcdf:
~~~~~
-- Performing Test C_COMPILER_SUPPORTS_OMP - Success
-- Found NetCDF4: 1  
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NetCDF (missing: NetCDF_LIBRARIES Fortran) (found version
  "4.7.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ecbuild/cmake/FindNetCDF.cmake:232 (find_package_handle_standard_args)
  saber/CMakeLists.txt:63 (find_package)


-- Configuring incomplete, errors occurred!
~~~~~

By behind, I mean two things.  First, it was behind ecmwf's develop version before I merged.   When I merged with ecmwf develop, I found conflicts with both of our additions, namely the FindNetCDF and associated additions (e.g HDF4) and the changes in the docs.  In order to isolate the changes and thus simply a subsequent PR to ecmwf, I removed the doc changes, leaving only the NetCDF changes. So, in that sense our develop is now caught up with ecmwf develop but it is behind our own release/stable branch.  I fixed the NetCDF conflicts by choosing our versions over theirs, but I must not have done it correctly.

Reverting my changes is messy because of the merge conflicts.  However, I don't think it's really necessary because I believe the current release/stable branch is identical to the develop branch before I started merging.  

So, I need help from @aerorahul and @markjolah to resolve these conflicts with ecmwf develop.  I'm not sure what the best way to proceed is.    I'm thinking we should get the FindNetCDF changes to work.  Then we could merge the release/stable into our develop to get the doc changes.  

In any case, do not delete the release/stable branch until all these changes are merged in to our develop.

**Comment by aerorahul** [comment]
@mmiesch @markjolah 
I have gotten back to looking at what is in in the `ecmwf:ecbuild`, that is now a cause of conflict when it comes to `NetCDF`.  It appears, `ecmwf:ecbuild` are no longer using the two-tier approach of finding NetCDF based on the versions.  They had a separate `FindNetCDF4.cmake`, that was used to find Version4 of the libraries.  They now, use a consolidated (and handicapped IMHO) version in `FindNetCDF.cmake`.  This version ONLY supports shared libraries, does not rely on `nc-config` to `find` the paths and dependency libraries e.g. HDF, HDF4, etc.  This is not going to work with GMAO stack (Baselibs), which is another way of building what is under jedi-stack.  As a result, the FV3-JEDI bundle with GEOS will be broken if we use `ecmwf:ecbuild`

What I propose is to replace `cmake/FindNetCDF.cmake` with `cmake/contrib/FindNetCDF4.cmake`.  This will work for both versions (3 and 4), static and shared library support, and use `nc-config` to find all dependencies.

If this is the path we choose, we should engage ECMWF in this discussion, otherwise we will be dealing with eternal conflicts.

Thoughts? Comments?

**Comment by mmiesch** [comment]
Thanks @aerorahul for looking at this.  From my perspective, the most important considerations are:
1) that the implementation work with jedi-stack
2) that the implementation in our fork does not conflict with ecmwf::develop 
To clarify what I mean by item 2; I don't mind if our fork diverges from ecmwf somewhat, but I want to be able to do a ```git pull upstream develop``` without getting a bunch of merge conflicts.    So, I agree that the best - maybe the only - way to approach this is to work with ecmwf to see if they are happy with the solution you propose.

Incidentally - I ran into that shared libs problem on Cheyenne - when building hdf5 with the intel19/mpt combination, I found I had to use static libraries and then ecbuild failed at finding them.  So, this might be useful in other situations as well.

**Comment by markjolah** [comment]
I had looked into this before thanksgiving.  Using the upstream works well for shared libraries.  I didn't realize the static libraries where not detected.  In general the new FindNetCDF.cmake is probably a better written find module, despite it's deficiencies.  I was kindof glad they got rid of the original contrib/FindNetCDF4.cmake, which in it's original state was very poor.  I think the best solution would be to work with the current FindNetCDF.cmake and add in static libraries support, possibly via the nc-config approach we used to patch the older FindNetCDF4.cmake.  I like that the new module is attempting to use namespaced imported interface targets like ` NetCDF::NetCDF_<comp>`.  This is the future direction for all cmake find modules.  I won't have time this week to make those changes myself, perhaps next week?  Do we have any time sensitivity for this issue?

**Comment by markjolah** [comment]
BTW.  The [official find module developer documentation](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) is a good resource for this and other CMake FindModule related programming, using the namespaces and imported interface targets.

**Comment by aerorahul** [comment]
I don't have any pressing need to push this, but whatever we end up should support both static and shared libraries as well as be able to find `all` dependencies with with the NetCDF library was built with. Yes, even the `curl` library if it was built in an obscure location.  This is only possible with the use of `nc-config`, otherwise, we will be adding a lot more `if` and `find_package` statements, and even then be limited in our approach to find the correct order and paths.  @markjolah, if you wish to take this on, feel free.

**Comment by markjolah** [comment]
Appending this reported problem from @jmrosinski  regarding his system which has netCDF installed as a system library and a separate Intel library.  Problem is that the `/usr/include` shows up in `CPATH` _before_ the NetCDF generated include path, mixing up the wrong modules.

**Comment by mmiesch** [comment]
@markjolah @aerorahul - I'd like to modify and close this issue because I believe our ecbuild develop branch is fixed in the sense that it does track ecmwf upstream as we discussed.  So, it is indeed functional.  But, somehow the static library issue and the netcdf issue got bundled into this issue - they should be separate.

**Comment by aerorahul** [comment]
@mmiesch I agree with you. This issue is fixed.  Let there be a new issue to handle static netcdf library.
